board_name = p520_max_sg280l

report: report_3a report_3b report_3c report_4b report_4c report_4d report_4e report_4f report_5b report_5c

report_3a:
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est   ./inception_3a.cl	
report_3b:
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_3b.cl
report_3c :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_3c.cl
report_4b :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est   ./inception_4b.cl
report_4c :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_4c.cl
report_4d :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_4d.cl
report_4e :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_4e.cl
report_4f :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_4f.cl
report_5b :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est ./inception_5b.cl
report_5c :
	aoc  -v -rtl -report -board=$(board_name) -dont-error-if-large-area-est  ./inception_5c.cl